version: '3.8'

services:
  # PostgreSQL database service
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passpass
      POSTGRES_DB: bankingDb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Prisma service (to manage migrations and database schema)
  prisma:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: ["npx", "prisma", "migrate"] # Prisma migration step
    depends_on:
      - db

  # Next.js application service
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:passpass@db:5432/bankingDb?schema=public"
    depends_on:
      - db
      - prisma
    command: ["npm", "run", "dev"]

volumes:
  db-data:
